e=set()
n1=int(input("Enter the number you want: "))
e.add(n1)
n2=int(input("Enter the number you want: "))
e.add(n2)
n4=int(input("Enter the number you want: "))
e.add(n4)
n4=int(input("Enter the number you want: "))
e.add(n4)
n8=int(input("Enter the number you want: "))
e.add(n8)
n8=int(input("Enter the number you want: "))
e.add(n8)
n8=int(input("Enter the number you want: "))
e.add(n8)
n8=int(input("Enter the number you want: "))
e.add(n8)
print(e)
print(type(e))